### ISSUE TITLE
ModuleNotFoundError: No module named ‘Note Organizer.forms'

### ISSUE THREAD

**Issue by Willz7** [ijgnd/anki21___note-organizer#1]
Thank you Ijgnd for updating this. 

I installed the addon by downloading the src file on github and drag and drog into the anki addon folder. 

Using Anki 2.1.22 and Window 10

![error when opening Anki](https://i.imgur.com/ikcHvak.png)

**Comment by ijgnd** [comment]
I missed your issue. Github didn't notify me. I just saw that I wasn't "watch"ing it. Usually repos I create are "watch"ed by my account autoamatically so that usually I automatically get notifications ...

The problem is that this add-ons contains UI elements that are made with the QtDesigner in the folder designer. These need to be converted to python files with the pyuic tool and put into the subfolder "forms" in the add-on.

You can download an easy to install ankiaddon file from [here](https://github.com/ijgnd/anki21___note-organizer/releases/download/0.4/anki21___note-organizer__2020-04-05_.ankiaddon).

Only use it if you've carefully read at least the first paragraph of [this file](https://raw.githubusercontent.com/ijgnd/anki21___note-organizer/master/README.md).

If you are interested in faking the creation time (note id) you might also be interested in these add-ons:

- https://github.com/ijgnd/anki__browser_fast_change_nid ([ankiaddon file](https://github.com/ijgnd/anki__browser_fast_change_nid/releases/download/0.1/anki__browser_fast_change_nid__2020-04-04.ankiaddon)).
- https://github.com/ijgnd/anki-copy-note ([ankiaddon file](https://github.com/ijgnd/anki-copy-note/releases/download/0.1/anki-copy-note__2020-06-06.ankiaddon))

Make sure to read the readmes carefully before using them. 

I made three different add-ons that are more or less about the same thing for two reasons: They have different approaches and and different UIs and I didn't know which one I would prefer. 

If you find bugs please let me know.
